import sharp from 'sharp';
import { extractFrames, createPreviewGif } from './video-extract';
import { analyzeImage, ImageAnalysis } from './vision-agent';

export interface VideoPreviewResult {
  posterBuffer: Buffer;
  gifBuffer: Buffer;
  analysis: ImageAnalysis;
  frameCount: number;
  duration: number;
}

export async function generateVideoPreview(
  videoBuffer: Buffer,
  context: { title: string; category: string }
): Promise<VideoPreviewResult> {
  console.log('[VIDEO-PREVIEW] Extracting frames...');
  const { frames, duration } = await extractFrames(videoBuffer, 8);

  if (frames.length === 0) {
    throw new Error('Could not extract any frames from video');
  }

  console.log(`[VIDEO-PREVIEW] Extracted ${frames.length} frames from ${duration.toFixed(1)}s video`);

  // Pick 4 evenly spaced frames for vision analysis (skip first/last which may be black)
  const analysisFrames = pickBestFrames(frames, 4);

  // Send the best frame to the vision agent for analysis
  let analysis: ImageAnalysis;
  try {
    analysis = await analyzeImage(analysisFrames[0], 'image/jpeg', context);
    console.log(`[VIDEO-PREVIEW] Vision agent: "${analysis.tagline}"`);
  } catch (err) {
    console.warn('[VIDEO-PREVIEW] Vision agent failed:', err);
    analysis = {
      tagline: `${context.category} video — ${context.title}`,
      description: `A ${context.category} video asset. Preview generated by TrustDrop AI.`,
      regions: [
        { x: 0.1, y: 0.1, w: 0.35, h: 0.35, label: 'Scene' },
        { x: 0.5, y: 0.15, w: 0.35, h: 0.3, label: 'Detail' },
        { x: 0.2, y: 0.55, w: 0.4, h: 0.35, label: 'Action' },
      ],
      mood: 'dramatic',
      dominantColors: ['#1a1a2e', '#16213e', '#0f3460'],
    };
  }

  // Generate the static poster (cinematic card from best frame)
  console.log('[VIDEO-PREVIEW] Composing poster...');
  const posterBuffer = await composePoster(analysisFrames, analysis, context, duration);

  // Generate the animated GIF from selected frames
  console.log('[VIDEO-PREVIEW] Creating preview GIF...');
  const gifFrames = pickBestFrames(frames, Math.min(frames.length, 5));
  const gifBuffer = await createPreviewGif(gifFrames, 600);

  console.log(`[VIDEO-PREVIEW] Done — poster + ${gifFrames.length}-frame GIF`);

  return {
    posterBuffer,
    gifBuffer,
    analysis,
    frameCount: frames.length,
    duration,
  };
}

function pickBestFrames(frames: Buffer[], count: number): Buffer[] {
  if (frames.length <= count) return [...frames];
  const step = frames.length / count;
  const picked: Buffer[] = [];
  for (let i = 0; i < count; i++) {
    const idx = Math.min(Math.floor(i * step), frames.length - 1);
    picked.push(frames[idx]);
  }
  return picked;
}

async function composePoster(
  frames: Buffer[],
  analysis: ImageAnalysis,
  context: { title: string; category: string },
  duration: number
): Promise<Buffer> {
  const heroFrame = frames[0];
  const metadata = await sharp(heroFrame).metadata();
  const origW = metadata.width || 800;
  const origH = metadata.height || 450;

  const canvasW = Math.min(origW, 1200);
  const canvasH = Math.max(1, Math.round((origH / origW) * canvasW));

  // Blurred dark background from hero frame
  const bgBuffer = await sharp(heroFrame)
    .resize(canvasW, canvasH, { fit: 'cover' })
    .blur(25)
    .modulate({ brightness: 0.25 })
    .toBuffer();

  // Film strip of 3-4 frames along the middle
  const stripFrames = frames.slice(0, Math.min(4, frames.length));
  const stripW = Math.floor((canvasW - 80) / stripFrames.length);
  const stripH = Math.floor(stripW * 0.56); // 16:9 aspect
  const stripY = Math.floor((canvasH - stripH) / 2);
  const composites: sharp.OverlayOptions[] = [];

  for (let i = 0; i < stripFrames.length; i++) {
    const frameX = 40 + i * stripW;
    const thumbW = stripW - 12;
    const thumbH = stripH - 8;

    if (thumbW < 10 || thumbH < 10) continue;

    const thumb = await sharp(stripFrames[i])
      .resize(thumbW, thumbH, { fit: 'cover' })
      .toBuffer();

    // Frame border
    const accent = analysis.dominantColors[i % analysis.dominantColors.length] || '#10b981';
    const border = 2;
    const frameW = thumbW + border * 2;
    const frameH = thumbH + border * 2;
    const radius = 8;

    const frameSvg = `<svg width="${frameW}" height="${frameH}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <filter id="glow${i}"><feGaussianBlur stdDeviation="3"/></filter>
      </defs>
      <rect x="0" y="0" width="${frameW}" height="${frameH}" rx="${radius}" ry="${radius}"
            fill="none" stroke="${accent}" stroke-width="${border}" filter="url(#glow${i})" opacity="0.7"/>
    </svg>`;

    const mask = `<svg width="${thumbW}" height="${thumbH}" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="${thumbW}" height="${thumbH}" rx="${radius}" ry="${radius}" fill="white"/>
    </svg>`;

    const maskedThumb = await sharp(thumb)
      .composite([{ input: Buffer.from(mask), blend: 'dest-in' }])
      .png()
      .toBuffer();

    const framedThumb = await sharp(Buffer.from(frameSvg))
      .composite([{ input: maskedThumb, left: border, top: border }])
      .png()
      .toBuffer();

    composites.push({
      input: framedThumb,
      left: frameX,
      top: stripY,
    });
  }

  // Overlay SVG with tagline, duration badge, and branding
  const tagline = escapeXml(analysis.tagline.slice(0, 70));
  const tagFontSize = Math.max(18, Math.floor(canvasW / 30));
  const brandFontSize = Math.max(12, Math.floor(canvasW / 50));
  const durationStr = formatDuration(duration);
  const gradH = Math.floor(canvasH * 0.28);

  const overlaySvg = `<svg width="${canvasW}" height="${canvasH}" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="topFade" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="black" stop-opacity="0.7"/>
        <stop offset="1" stop-color="black" stop-opacity="0"/>
      </linearGradient>
      <linearGradient id="bottomFade" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0" stop-color="black" stop-opacity="0"/>
        <stop offset="1" stop-color="black" stop-opacity="0.85"/>
      </linearGradient>
    </defs>

    <!-- Top gradient -->
    <rect x="0" y="0" width="${canvasW}" height="${Math.floor(canvasH * 0.15)}" fill="url(#topFade)"/>

    <!-- Bottom gradient -->
    <rect x="0" y="${canvasH - gradH}" width="${canvasW}" height="${gradH}" fill="url(#bottomFade)"/>

    <!-- Video badge -->
    <rect x="16" y="14" width="${60 + durationStr.length * 8}" height="28" rx="6" ry="6" fill="rgba(0,0,0,0.6)"/>
    <text x="36" y="33" font-size="13" fill="white" font-family="system-ui, sans-serif" font-weight="600">
      ${durationStr}
    </text>
    <!-- Play triangle -->
    <polygon points="22,22 22,36 32,29" fill="rgba(16,185,129,0.9)"/>

    <!-- Encrypted Preview -->
    <text x="${canvasW - 16}" y="33" font-size="${brandFontSize}" fill="rgba(255,255,255,0.5)"
      font-family="system-ui, sans-serif" font-weight="500" text-anchor="end">
      Encrypted Preview
    </text>

    <!-- Tagline -->
    <text x="${Math.floor(canvasW / 2)}" y="${canvasH - 36}" font-size="${tagFontSize}" fill="white"
      font-family="system-ui, sans-serif" font-weight="700"
      text-anchor="middle" letter-spacing="0.5">${tagline}</text>

    <!-- Brand -->
    <text x="${canvasW - 16}" y="${canvasH - 12}" font-size="${brandFontSize}" fill="rgba(16,185,129,0.7)"
      font-family="system-ui, sans-serif" font-weight="600"
      text-anchor="end" letter-spacing="2">TrustDrop</text>
  </svg>`;

  composites.push({ input: Buffer.from(overlaySvg), gravity: 'center' });

  const poster = await sharp(bgBuffer)
    .composite(composites)
    .jpeg({ quality: 85 })
    .toBuffer();

  return poster;
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, '0')}`;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
